feat(base-repo): included the base repository in chargejs
charge-tech/chargejs pull request #18
Opened 2021-02-09 03:48 UTC by dmytro-kulchytskyi

https://charge.atlassian.net/browse/WALL-1062

2021-02-09 04:56 UTC, NFhbar requested changes
Awesome!
Just a few comments on moving all `strings` to the `error` and/or `constants` file.
Also, is this a `major` change?

2021-02-09 04:56 UTC, NFhbar commented on src/infra/BaseRepository.js
> +        case 'SequelizeValidationError':
put these strings in the `errors` file.

2021-02-09 04:56 UTC, NFhbar commented on src/infra/BaseRepository.js
> +      const error = new Error('patchAllowedFields was not configured in init function')
put these `strings` in the errors file.

2021-02-09 04:56 UTC, NFhbar commented on src/infra/BaseRepository.js
> +    const error = new Error('disableCache option was set to true, please provide provide disableCache: false option to use caching.')
put these `strings` in the error file.

2021-02-09 04:56 UTC, NFhbar commented on src/infra/redis/RedisRepository.js
> +      const error = new Error(`Invalid filter. Configure cache keys to support provided filter fields: "${JSON.stringify(keys)}"`)
put in `error` file.

2021-02-09 04:56 UTC, NFhbar commented on src/infra/redis/RedisStorage.js
> +        event: 'create',
put these in the `strings` in error file.

2021-02-09 14:17 UTC, dmytro-kulchytskyi commented
> Awesome!
> Just a few comments on moving all `strings` to the `error` and/or `constants` file.
> Also, is this a `major` change?

@NFhbar There are a lot of changes, but I haven't broken any existing functionality, so I think it's a minor

2021-02-09 15:43 UTC, NFhbar approved these changes

2021-02-09 20:54 UTC, amanelis approved these changes
epic ☄️

2021-02-09 21:31 UTC, supaflyENJOY approved these changes

2021-02-10 15:17 UTC, valera-rozuvan approved these changes

2021-02-11 03:14 UTC, merged

2021-02-11 03:15 UTC, charge-machine-user commented
:tada: This PR is included in version 1.12.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@charge-tech/chargejs/v/1.12.0)
- [GitHub release](https://github.com/charge-tech/chargejs/releases/tag/v1.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: