feat(error): added standard error function to interface layer
charge-tech/chargejs pull request #4
Opened 2020-10-09 17:25 UTC by dmytro-kulchytskyi

2020-10-09 17:27 UTC, amanelis approved these changes

2020-10-09 17:42 UTC, NFhbar requested changes

2020-10-09 17:42 UTC, NFhbar commented on src/interfaces.js
> + * @param {Object} input.errors The errors array
This should be `@param {Object[]}` which expects an array with objects of this type:

```js
{
   param, 
  msg,
  location
}
```

define a custom type and use this type in the param definition:
https://jsdoc.app/tags-typedef.html

2020-10-09 17:43 UTC, NFhbar requested changes

2020-10-09 17:43 UTC, NFhbar commented on src/interfaces.js
> + * @param {Object} input.type The error type
`type` should be string, `message` too

2020-10-12 14:27 UTC, NFhbar approved these changes

2020-10-12 14:32 UTC, merged

2020-10-12 14:34 UTC, charge-machine-user commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@charge-tech/chargejs/v/1.2.0)
- [GitHub release](https://github.com/charge-tech/chargejs/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: